# Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,2,3,4,5,6,7,8,9]])

In [3]:
print(myarr)

[[1 2 3 4 5 6 7 8 9]]


In [4]:
myarr[0,3]

4

In [5]:
myarr.shape

(1, 9)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr[0,3] = 10

In [8]:
myarr[0,3]

10

# Array Creation 5 ways

# 1 : Conversion from other python structures

In [9]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr1.shape

(3, 3)

In [12]:
arr1.size

9

In [13]:
arr1.dtype

dtype('int32')

In [14]:
arr1[1,2]

6

In [15]:
arr1[1,2] = 10

In [16]:
arr1[1,2]

10

# 2 way , zeros ones arrange

In [17]:
zeros = np.zeros((3,4),np.int8)

In [18]:
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [19]:
zeros.shape

(3, 4)

In [20]:
zeros.dtype

dtype('int8')

In [21]:
zeros[1,3]

0

In [22]:
zeros[1,3] = 5

In [23]:
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 5],
       [0, 0, 0, 0]], dtype=int8)

**---------------------- arrange ---------------------------**

In [24]:
rnge = np.arange((10))

In [25]:
rnge

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
rnge.shape

(10,)

In [27]:
rnge.size

10

In [28]:
rnge2 = np.arange(10,12)

In [29]:
rnge2

array([10, 11])

In [30]:
rnge3 = np.arange(1,10,2)

In [31]:
rnge3

array([1, 3, 5, 7, 9])

**---------------------- Linspace ---------------------------**

In [32]:
lspace = np.linspace(1,10)

In [33]:
lspace

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [34]:
lspace.shape

(50,)

In [35]:
lspace.size

50

In [36]:
lspace1 = np.linspace(0,20,10)

In [37]:
lspace1

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [38]:
lspace1.size

10

In [39]:
lspace1.shape

(10,)

In [40]:
lspace1[2]

4.444444444444445

In [41]:
lspace[2] = 40

In [42]:
lspace[2]

40.0

**---------------------- Identity ---------------------------**

In [43]:
iden = np.identity(5)

In [44]:
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
iden.dtype

dtype('float64')

# Reshape

In [46]:
abc = np.arange((120))

In [47]:
abc

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [48]:
abc = abc.reshape(12,10)

In [49]:
abc

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [50]:
abc.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

# Numpy Axix

In [51]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [52]:
ar = np.array(x)

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [54]:
ar.sum(axis=0) # add downwards (0 = vertically, 1 = horizontally)

array([12,  8,  9])

In [55]:
ar.sum(axis=1)

array([ 6, 15,  8])

**-------------------------- Transpose ---------------------------**

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
ar.T # row converted into column && column converted into row

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

** --------------------- Array Flat ---------------------------- **

In [58]:
for i in ar:
    print(i)

[1 2 3]
[4 5 6]
[7 1 0]


In [59]:
ar.flat

In [60]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [61]:
ar.ndim # show dimension

2

In [62]:
ar.size

9

In [63]:
ar.shape

(3, 3)

In [64]:
ar.nbytes

36

In [65]:
one = np.array([12,34,76,13,45])

In [66]:
one.argmax() # show the maximum value index

2

In [67]:
one.argmin() # shows the minimum value index

0

In [68]:
one.argsort() # shows indexes if shifted in this, then it is sorted

array([0, 3, 1, 4, 2], dtype=int64)

In [69]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
ar = ar.ravel()

In [71]:
ar

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [72]:
ar.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [73]:
a1 = np.array([[1,2,3],[3,4,5]])
a2 = np.array([[2,1,5],[1,2,7]])

In [74]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [75]:
a2

array([[2, 1, 5],
       [1, 2, 7]])

In [76]:
a1+a2

array([[ 3,  3,  8],
       [ 4,  6, 12]])

In [77]:
a1*a2

array([[ 2,  2, 15],
       [ 3,  8, 35]])

In [78]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798]])

In [79]:
a1.max()

5

In [80]:
a1.min()

1

In [81]:
a1.mean()

3.0

In [82]:
a1.sum()

18

In [83]:
ar

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [84]:
np.where(ar>5)

(array([5, 6], dtype=int64),)

In [85]:
a2

array([[2, 1, 5],
       [1, 2, 7]])

In [86]:
np.where(a2>6)

(array([1], dtype=int64), array([2], dtype=int64))

In [87]:
np.count_nonzero(a2)

6